import * as React from "react"
import { ChevronLeft, Check } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"
import { Separator } from "@/components/ui/separator"
import type { AppState } from "@/types/blueprint"

export interface ResponsePhaseProps {
  state: AppState
  updateState: (k: keyof AppState, v: unknown) => void
  onBack: () => void
  onParse: () => void
}

export const ResponsePhase = React.memo<ResponsePhaseProps>(({ state, updateState, onBack, onParse }) => (
  <div className="max-w-4xl animate-in pb-20">
    <h2 className="text-3xl font-bold mb-2 tracking-tight">Process AI Response</h2>
    <p className="text-text-secondary mb-6">Paste the raw markdown response generated by the AI here. We parse <span className="font-mono text-text-primary">--- FILE: ---</span> blocks into downloadable files.</p>
    <Separator className="mb-8" />
    <div className="rounded-xl border border-border-strong bg-surface-1 p-1 shadow-sm">
      <Textarea
        label="Paste AI Response"
        placeholder={"--- FILE: PROJECT_CONTEXT.md ---\n# Project Context\n...\n--- END FILE ---\n\n--- FILE: PRODUCT_REQUIREMENTS.md ---\n..."}
        value={state.aiResponse}
        onChange={(e: any) => updateState("aiResponse", e.target.value)}
        rows={15}
      />
      <div className="px-3 pb-3 flex items-center justify-between text-[11px] font-mono text-text-muted">
        <span>{state.aiResponse.length.toLocaleString()} chars · {state.aiResponse.split("--- FILE:").length - 1} file blocks detected</span>
        <span className="hidden sm:inline">Supports fallback to AI_OUTPUT_RAW.md</span>
      </div>
    </div>
    <div className="flex justify-between mt-8 pt-6 border-t border-border-subtle">
      <Button variant="ghost" onClick={onBack} className="gap-2"><ChevronLeft size={18} /> Back</Button>
      <Button onClick={onParse} disabled={!state.aiResponse.trim()} className="gap-2 shadow-md">Parse Blueprint <Check size={18} /></Button>
    </div>
  </div>
))
ResponsePhase.displayName = "ResponsePhase"
export default ResponsePhase
